/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const fs = require('fs');
const path = require('path');

// Dynamically generate sidebars from docs folder structure
function generateSidebars() {
  const docsPath = path.join(__dirname, 'docs');
  const sidebars = {};
  
  try {
    const entries = fs.readdirSync(docsPath, { withFileTypes: true });
    
    for (const entry of entries) {
      if (entry.isDirectory() && !entry.name.startsWith('.')) {
        // Extract the sidebar ID (e.g., "1_ggtv" -> "ggtv")
        const sidebarId = entry.name.replace(/^\d+_/, '');
        
        console.log(`Generating sidebar: ${entry.name} -> ${sidebarId}`);
        
        sidebars[sidebarId] = [
          {
            type: 'autogenerated',
            dirName: entry.name
          },
        ];
      }
    }
    
    console.log('Generated sidebars:', Object.keys(sidebars));
  } catch (error) {
    console.warn('Could not read docs directory:', error);
  }
  
  return sidebars;
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = generateSidebars();

module.exports = sidebars;